name = "TheBlockSurvival"
author = "Slash"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d495798b3f9b8741d3980efff3a4d2db46e5d6f682fc6cc1edcaa273e28b589b"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2.0"]
