name = "TheBlockSurvival"
author = "Slash"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e6f0cdeaf8ad1911c0502881242bed71030857e802d8719c6a3af549bdf566e"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2.0"]
