name = "TheBlockSurvival"
author = "Slash"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ea182c9d50334e773c2645a9f0de470f35a17109af3024b66793e7eab007e01"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2.0"]
